import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import process from 'node:process';
import console from 'node:console';
import {pathToFileURL,URL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE_PATH ?? path.join(os.tmpdir(),'pet-clinical-regression/node_modules/@electric-sql/pglite/dist/index.js')).href);
const db=new PGlite();
const owner='00000000-0000-0000-0000-000000000001';
const home='00000000-0000-0000-0000-000000000002';
const uuid=async()=>(await db.query('select gen_random_uuid() id')).rows[0].id;
const scalar=async(sql,args=[])=>(await db.query(sql,args)).rows[0]?.value;
const role=async(name)=>{await db.exec(`reset role; select set_config('request.jwt.claim.role','${name}',false); select set_config('request.jwt.claim.sub','${name==='anon'?'':owner}',false); set role ${name==='service_role'?'postgres':name}`);};
const object=async(name,bucket='pet-alert-media')=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',[bucket,name]);
const resolve=(name)=>scalar('select resolve_pet_sos_public_photo($1) value',[name]);
const checks=[];
const reject=async(name,fn,re)=>{await assert.rejects(fn,re);checks.push(name);};
async function migration(name){await db.exec(await fs.readFile(new URL(`../migrations/${name}.sql`,import.meta.url),'utf8'));}
try {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth; create schema storage;
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
    create table auth.users(id uuid primary key); insert into auth.users values('${owner}');
    create table pets(id uuid primary key,household_id uuid);
    create table pet_profiles(pet_id uuid primary key,avatar_storage_bucket text,avatar_storage_path text);
    create table pet_alert_lost_pets(id uuid primary key,pet_id uuid,household_id uuid,alert_slug text,source_type text default 'registered_pet',status text default 'draft',share_enabled boolean default true,expires_at timestamptz default now()+interval '1 day');
    create table pet_alert_community_sightings(id uuid primary key,report_slug text,reporter_user_id uuid,status text default 'sighting_open',share_enabled boolean default true,expires_at timestamptz default now()+interval '1 day');
    create table pet_alert_media(id uuid primary key default gen_random_uuid(),lost_pet_alert_id uuid,storage_bucket text default 'pet-alert-media',storage_path text unique,visibility text default 'public',media_type text default 'image/jpeg');
    create table pet_alert_community_sighting_media(id uuid primary key default gen_random_uuid(),community_sighting_id uuid,report_slug text,storage_bucket text default 'pet-alert-media',storage_path text unique,file_name text,mime_type text,file_size_bytes bigint,display_order integer,created_by_user_id uuid,unique(community_sighting_id,display_order));
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,updated_at timestamptz default now(),unique(bucket_id,name));
    alter table storage.objects enable row level security;
    create policy permissive_fixture on storage.objects for all to anon,authenticated using(bucket_id='pet-alert-media') with check(bucket_id='pet-alert-media');
    grant usage on schema storage,auth to anon,authenticated;
    grant select,insert,update,delete on storage.objects to anon,authenticated;
    grant insert on pet_alert_media to authenticated;
    create function can_manage_pet_alert_community_sighting(uuid,uuid) returns boolean language sql as $$select $2='${owner}'::uuid$$;
    create function can_manage_pet_alert_lost_pet(uuid,uuid) returns boolean language sql as $$select $2='${owner}'::uuid$$;
    create function can_edit_pet(uuid,uuid) returns boolean language sql as $$select $2='${owner}'::uuid$$;
    create function can_admin_review_pet_alert_external_media(text,text) returns boolean language sql as $$select false$$;
    create function is_pet_alert_lost_media_public(text,text) returns boolean language sql as $$select false$$;
    create table audit_logs(action text);
    create function insert_audit_log(text,uuid,text,jsonb,uuid) returns void language sql as $$insert into audit_logs values($3)$$;
    create function publish_pet_alert_lost_pet(uuid) returns pet_alert_lost_pets language plpgsql as $$declare a pet_alert_lost_pets; begin update pet_alert_lost_pets set status='active' where id=$1 and status='draft' returning * into a; if a.id is null then raise exception 'PET_ALERT_NOT_ACTIVE'; end if; return a; end;$$;
    select set_config('request.jwt.claim.sub','${owner}',false);
  `);
  await migration('20260823234500_pet_alert_public_pet_avatar');
  await migration('20260824100000_pet_alert_anon_storage_policy_fix');
  await migration('20260921120000_pet_sos_community_photo_uploads');
  await migration('20260921140000_pet_sos_owner_avatar_derivatives');
  await migration('20260921160000_pet_sos_ready_media_projection');
  await migration('20260921180000_pet_sos_media_maintenance');
  const pet=await uuid(),alert=await uuid();
  await role('service_role');
  assert.equal(await scalar('select pet_sos_ready_media_only() value'),false);
  await db.query('insert into pets values($1,$2)',[pet,home]);
  await db.query("insert into pet_profiles values($1,'pet-avatars',$2)",[pet,`${pet}/photo.jpg`]);
  await object(`${pet}/photo.jpg`,'pet-avatars');
  await db.query("insert into pet_alert_lost_pets(id,pet_id,household_id,alert_slug,status) values($1,$2,$3,'owner','active')",[alert,pet,home]);
  await role('anon');
  assert.equal((await db.query("select * from storage.objects where bucket_id='pet-avatars'")).rows.length,1);
  await reject('legacy helper no longer callable',()=>db.query("select is_pet_alert_avatar_public_legacy_1c3d('pet-avatars',$1)",[`${pet}/photo.jpg`]),/permission denied/);
  await reject('anon cannot switch mode',()=>db.query('select set_pet_sos_ready_media_only(true,true)'),/permission denied/);
  await role('service_role');
  const job=await scalar('select prepare_pet_alert_owner_photo($1,$2,true) value',[alert,owner]);
  await object(job.display_path); await object(job.thumbnail_path);
  await db.query('select finalize_pet_alert_owner_photo($1,$2,$3,100,50)',[alert,owner,job.attempt_id]);
  assert.equal(await resolve(job.display_path),null);
  await db.query("update pet_alert_lost_pets set status='draft' where id=$1",[alert]);
  await role('authenticated');
  await reject('safe publish refuses pre-cutover',()=>db.query('select publish_pet_alert_lost_pet_safe($1,true)',[alert]),/NOT_ENABLED/);
  await role('service_role');
  await reject('cutover needs acknowledgement',()=>db.query('select set_pet_sos_ready_media_only(true,false)'),/ACK_REQUIRED/);
  await db.query('select set_pet_sos_ready_media_only(true,true)');
  await role('authenticated');
  await db.query('select publish_pet_alert_lost_pet_safe($1,true)',[alert]);
  await role('anon');
  assert.equal((await db.query("select * from storage.objects where bucket_id='pet-avatars'")).rows.length,0);
  assert.equal((await db.query('select * from storage.objects where name=$1',[job.display_path])).rows.length,0);
  const manifest=(await db.query("select * from list_public_pet_alert_lost_pet_media(array['owner'])")).rows;
  assert.equal(manifest.length,1); assert.equal(manifest[0].storage_path,job.display_path);
  await reject('anonymous photo choice denied',()=>db.query('select set_pet_sos_owner_photo_choice($1,false)',[alert]),/permission denied/);
  await role('authenticated');
  await db.query("select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000099',false)");
  await reject('unrelated actor photo choice denied',()=>db.query('select set_pet_sos_owner_photo_choice($1,false)',[alert]),/UNAUTHORIZED/);
  await role('authenticated');
  await db.query('select set_pet_sos_owner_photo_choice($1,true)',[alert]);
  await role('anon');
  await reject('legacy direct storage insert closed',()=>object('legacy.jpg'),/row-level security/);
  await role('authenticated');
  await reject('cannot forge ready external metadata',()=>db.query("insert into pet_alert_media(storage_path,processing_version) values('forged','sos-v1')"),/SERVER_MEDIA_REQUIRED/);
  await role('service_role');
  for(const state of ['flagged','draft','expired']) {
    await db.query('update pet_alert_lost_pets set status=$2 where id=$1',[alert,state]);
    assert.equal(await resolve(job.display_path),null);
  }
  await db.query("update pet_alert_lost_pets set status='active',share_enabled=false where id=$1",[alert]);
  assert.equal(await resolve(job.display_path),null);
  await db.query('update pet_alert_lost_pets set share_enabled=true where id=$1',[alert]);
  await db.query("update storage.objects set updated_at=now()+interval '1 minute' where id=$1",[job.source_object_id]);
  assert.equal(await resolve(job.display_path),null);
  await db.query('update storage.objects set updated_at=$2 where id=$1',[job.source_object_id,job.source_updated_at]);
  await role('authenticated');
  await reject('safe publish preserves draft-only transition',()=>db.query('select publish_pet_alert_lost_pet_safe($1,false)',[alert]),/NOT_ACTIVE/);
  await role('service_role');
  await db.query("update pet_alert_lost_pets set status='draft' where id=$1",[alert]);
  await role('authenticated');
  await db.query('select publish_pet_alert_lost_pet_safe($1,false)',[alert]);
  await role('service_role'); assert.equal(await resolve(job.display_path),null);
  await db.query('select set_pet_sos_ready_media_only(false,true)');
  assert.equal((await db.query("select * from list_public_pet_alert_lost_pet_media(array['owner'])")).rows.length,0);
  assert.equal(await scalar("select is_pet_alert_avatar_public('pet-avatars',$1) value",[`${pet}/photo.jpg`]),false);
  await db.query('select set_pet_sos_ready_media_only(true,true)');
  await role('authenticated');
  await reject('cannot include a failed/withdrawn derivative',()=>db.query('select set_pet_sos_owner_photo_choice($1,true)',[alert]),/NOT_READY/);
  await db.query('select set_pet_sos_owner_photo_choice($1,false)',[alert]);
  await role('service_role');
  assert.equal(await scalar('select owner_photo_choice value from pet_alert_lost_pets where id=$1',[alert]),'exclude');
  const report=await uuid();
  await db.query("insert into pet_alert_community_sightings(id,report_slug,reporter_user_id) values($1,'community',$2)",[report,owner]);
  const upload=await scalar('select prepare_pet_alert_community_photo($1,$2,$3,0) value',[report,owner,'a'.repeat(64)]);
  await object(upload.storage_path);
  await reject('thumbnail required transactionally',()=>db.query('select finalize_pet_alert_community_photo($1,$2,$3,100)',[upload.id,owner,upload.attempt_id]),/NOT_UPLOADED/);
  assert.equal(await scalar('select count(*)::int value from pet_alert_community_sighting_media'),0);
  await object(`${upload.storage_path}.thumb.jpg`);
  await db.query('select finalize_pet_alert_community_photo($1,$2,$3,100)',[upload.id,owner,upload.attempt_id]);
  assert.equal(await resolve(upload.storage_path),upload.storage_path);
  const external=await uuid();
  await db.query("insert into pet_alert_lost_pets(id,alert_slug,source_type,status) values($1,'external','external_owner','active')",[external]);
  await object('external/ready.jpg'); await object('external/ready.jpg.thumb.jpg');
  await db.query("insert into pet_alert_media(lost_pet_alert_id,storage_path,thumbnail_path,processing_version) values($1,'external/ready.jpg','external/ready.jpg.thumb.jpg','sos-v1')",[external]);
  assert.equal(await resolve('external/ready.jpg'),'external/ready.jpg');
  await db.query("update pet_alert_lost_pets set status='pending_review' where id=$1",[external]);
  assert.equal(await resolve('external/ready.jpg'),null);
  await object('owner-sos-v1/orphan.jpg');
  await db.query("update storage.objects set updated_at=now()-interval '25 hours' where name in('owner-sos-v1/orphan.jpg',$1)",[upload.storage_path]);
  const orphans=(await db.query('select * from list_pet_sos_orphan_media_candidates(100)')).rows;
  assert.deepEqual(orphans.map((row)=>row.storage_path),['owner-sos-v1/orphan.jpg']);
  assert.equal((await scalar('select inspect_pet_sos_media_rollout() value')).cleanupDryRun,true);
  await role('anon');
  await reject('inventory service only',()=>db.query('select inspect_pet_sos_media_rollout()'),/permission denied/);
  await reject('public resolver service only',()=>resolve(upload.storage_path),/permission denied/);
  await reject('backfill service only',()=>db.query("select prepare_pet_sos_media_backfill('community',$1)",[upload.id]),/permission denied/);
  await reject('cleanup service only',()=>db.query('select claim_pet_sos_orphan($1,now())',[upload.id]),/permission denied/);
  await role('service_role');
  const legacyReport=await uuid(),legacyMedia=await uuid();
  await db.query("insert into pet_alert_community_sightings(id,report_slug,reporter_user_id) values($1,'legacy',$2)",[legacyReport,owner]);
  const legacyPath=`${legacyReport}/original.png`;
  await object(legacyPath);
  await db.query("insert into pet_alert_community_sighting_media(id,community_sighting_id,report_slug,storage_path,display_order) values($1,$2,'legacy',$3,0)",[legacyMedia,legacyReport,legacyPath]);
  const prepareBackfill=()=>scalar("select prepare_pet_sos_media_backfill('community',$1) value",[legacyMedia]);
  const backfill=await prepareBackfill();
  await reject('backfill lease prevents duplicates',prepareBackfill,/BUSY/);
  await object(backfill.display_path); await object(backfill.thumbnail_path);
  await db.query('update pet_alert_community_sightings set share_enabled=false where id=$1',[legacyReport]);
  await reject('backfill respects withdrawal',()=>db.query('select finalize_pet_sos_media_backfill($1,100)',[backfill.id]),/NOT_AVAILABLE/);
  await db.query('update pet_alert_community_sightings set share_enabled=true where id=$1',[legacyReport]);
  await db.query("update storage.objects set updated_at=now()+interval '1 minute' where name=$1",[legacyPath]);
  await reject('backfill rejects changed source',()=>db.query('select finalize_pet_sos_media_backfill($1,100)',[backfill.id]),/STALE/);
  await db.query('select abort_pet_sos_media_backfill($1)',[backfill.id]);
  const retry=await prepareBackfill();
  assert.notEqual(retry.display_path,backfill.display_path);
  await object(retry.display_path);
  await reject('backfill requires both variants',()=>db.query('select finalize_pet_sos_media_backfill($1,100)',[retry.id]),/NOT_UPLOADED/);
  await object(retry.thumbnail_path);
  await db.query('select finalize_pet_sos_media_backfill($1,100)',[retry.id]);
  await db.query('select finalize_pet_sos_media_backfill($1,100)',[retry.id]);
  await db.query('select abort_pet_sos_media_backfill($1)',[retry.id]);
  assert.equal(await resolve(retry.display_path),retry.display_path);
  assert.equal((await prepareBackfill()).status,'already_ready');
  assert.equal(await scalar('select count(*)::int value from storage.objects where name=$1',[legacyPath]),1);
  await role('anon');
  assert.equal((await db.query("select * from list_public_pet_alert_community_media(array['legacy'])")).rows[0].storage_path,retry.display_path);
  await role('service_role');
  const externalMedia=await uuid();
  await object('external/legacy.png');
  await db.query("insert into pet_alert_media(id,lost_pet_alert_id,storage_path) values($1,$2,'external/legacy.png')",[externalMedia,external]);
  const extJob=await scalar("select prepare_pet_sos_media_backfill('external',$1) value",[externalMedia]);
  await object(extJob.display_path); await object(extJob.thumbnail_path);
  await db.query('select finalize_pet_sos_media_backfill($1,100)',[extJob.id]);
  assert.equal(await resolve(extJob.display_path),null); // Pending moderation stays pending.
  await reject('Owner cannot be bulk-converted without consent',()=>db.query("select prepare_pet_sos_media_backfill('owner',$1)",[alert]),/INVALID_KIND/);
  const orphan=orphans[0];
  await reject('cleanup checks object version',()=>db.query('select claim_pet_sos_orphan($1,now())',[orphan.object_id]),/STALE/);
  const tomb=await scalar('select claim_pet_sos_orphan($1,$2) value',[orphan.object_id,orphan.object_updated_at]);
  await reject('tombstone blocks reattachment',()=>db.query('insert into pet_alert_media(storage_path) values($1)',[orphan.storage_path]),/RETIRED/);
  await reject('tombstone blocks replacement',()=>db.query('update storage.objects set updated_at=now() where id=$1',[orphan.object_id]),/RETIRED/);
  await reject('cleanup cannot claim success while object exists',()=>db.query('select finish_pet_sos_orphan_cleanup($1)',[tomb.id]),/NOT_DELETED/);
  await db.query('delete from storage.objects where id=$1',[orphan.object_id]); // Fixture simulates Storage API, not production SQL deletion.
  await db.query('select finish_pet_sos_orphan_cleanup($1)',[tomb.id]);
  await db.query('select finish_pet_sos_orphan_cleanup($1)',[tomb.id]);
  await reject('tombstone permanent after cleanup',()=>object(orphan.storage_path),/RETIRED/);
  const protectedObject=(await db.query('select id,updated_at from storage.objects where name=$1',[retry.display_path])).rows[0];
  await reject('ready referenced derivative cannot be cleaned',()=>db.query('select claim_pet_sos_orphan($1,$2)',[protectedObject.id,protectedObject.updated_at]),/STALE/);
  const interruptedMedia=await uuid();
  await object('external/interrupted.png');
  await db.query("insert into pet_alert_media(id,lost_pet_alert_id,storage_path) values($1,$2,'external/interrupted.png')",[interruptedMedia,external]);
  const interrupted=await scalar("select prepare_pet_sos_media_backfill('external',$1) value",[interruptedMedia]);
  await object(interrupted.display_path);
  await db.query("update pet_sos_media_backfills set lease_until=now()-interval '1 day' where id=$1",[interrupted.id]);
  await db.query("update storage.objects set updated_at=now()-interval '25 hours' where name=$1",[interrupted.display_path]);
  const interruptedObject=(await db.query('select id,updated_at from storage.objects where name=$1',[interrupted.display_path])).rows[0];
  await db.query('select claim_pet_sos_orphan($1,$2)',[interruptedObject.id,interruptedObject.updated_at]);
  await reject('expired claimed attempt cannot finalize',()=>db.query('select finalize_pet_sos_media_backfill($1,100)',[interrupted.id]),/STALE/);
  const replacement=await scalar("select prepare_pet_sos_media_backfill('external',$1) value",[interruptedMedia]);
  assert.notEqual(replacement.display_path,interrupted.display_path);
  checks.push('legacy off by default; owner consent/publication; original and direct signatures closed; immutable source revocation; community variants; external moderation; conservative orphan inventory');
  console.log(`PASS: ${checks.length} groups plus ready projection, RLS and inventory assertions (isolated fixtures, no hosted concurrency).`);
} finally {await db.close();}
