import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import process from 'node:process';
import console from 'node:console';
import {pathToFileURL, URL} from 'node:url';
const {PGlite} = await import(pathToFileURL(process.env.PGLITE_MODULE_PATH ?? path.join(os.tmpdir(), 'pet-clinical-regression/node_modules/@electric-sql/pglite/dist/index.js')).href);
const db = new PGlite();
const actor = '00000000-0000-0000-0000-000000000001';
const stranger = '00000000-0000-0000-0000-000000000002';
const hash = 'a'.repeat(64);
const prepare = async (id, user = actor, order = 0, digest = hash) => (await db.query('select prepare_pet_alert_community_photo($1,$2,$3,$4) as job', [id,user,digest,order])).rows[0].job;
const finalize = (job) => db.query('select finalize_pet_alert_community_photo($1,$2,$3,100)',[job.id,actor,job.attempt_id]);
const abort = async (job) => (await db.query('select abort_pet_alert_community_photo($1,$2,$3) as path',[job.id,actor,job.attempt_id])).rows[0].path;
const object = (job) => db.query("insert into storage.objects(bucket_id,name) values('pet-alert-media',$1)",[job.storage_path]);
const seed = async () => (await db.query("insert into pet_alert_community_sightings(reporter_user_id,report_slug) values($1,gen_random_uuid()::text) returning id",[actor])).rows[0].id;
try {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth; create schema storage;
    create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
    create table auth.users(id uuid primary key);
    insert into auth.users values('${actor}'),('${stranger}');
    create table pet_alert_community_sightings(id uuid primary key default gen_random_uuid(), reporter_user_id uuid,report_slug text,status text default 'sighting_open',expires_at timestamptz default now()+interval '1 day',share_enabled boolean default true);
    create table pet_alert_community_sighting_media(id uuid primary key default gen_random_uuid(),community_sighting_id uuid,report_slug text,storage_bucket text default 'pet-alert-media',storage_path text unique,file_name text,mime_type text,file_size_bytes bigint,display_order integer,created_by_user_id uuid,unique(community_sighting_id,display_order));
    create table storage.objects(bucket_id text,name text);
    alter table storage.objects enable row level security;
    create policy baseline on storage.objects for all to anon,authenticated using(true) with check(true);
    grant usage on schema storage,auth to anon,authenticated;
    grant select,insert,update,delete on storage.objects to anon,authenticated;
    create function can_manage_pet_alert_community_sighting(uuid,uuid) returns boolean language sql as $$select reporter_user_id=$2 from pet_alert_community_sightings where id=$1$$;
    create function is_pet_alert_community_media_public(text,text) returns boolean language sql security definer as $$select exists(select 1 from pet_alert_community_sighting_media m join pet_alert_community_sightings r on r.id=m.community_sighting_id where m.storage_bucket=$1 and m.storage_path=$2 and r.share_enabled)$$;
    create table audit_logs(action text);
    create function insert_audit_log(text,uuid,text,jsonb,uuid) returns void language sql as $$insert into audit_logs values($3)$$;
  `);
  await db.exec(await fs.readFile(new URL('../migrations/20260921120000_pet_sos_community_photo_uploads.sql',import.meta.url),'utf8'));
  const report = await seed();
  await assert.rejects(()=>prepare(report),/UNAUTHORIZED/);
  await db.exec("select set_config('request.jwt.claim.role','service_role',false)");
  await assert.rejects(()=>prepare(report,stranger),/UNAUTHORIZED/);
  await assert.rejects(()=>prepare(report,actor,3),/INVALID/);
  const first = await prepare(report);
  await assert.rejects(()=>prepare(report),/BUSY/);
  await assert.rejects(()=>prepare(report,actor,0,'b'.repeat(64)),/SLOT_TAKEN/);
  await assert.rejects(()=>finalize(first),/NOT_UPLOADED/);
  await object(first); await finalize(first); await finalize(first);
  assert.equal((await prepare(report)).status,'ready');
  assert.equal((await db.query('select count(*)::int as n from audit_logs')).rows[0].n,1);
  assert.equal(await abort(first),null);
  const second = await prepare(report,actor,1);
  await object(second);
  await db.query("update pet_alert_community_sightings set status='closed' where id=$1",[report]);
  await assert.rejects(()=>finalize(second),/REPORT_NOT_AVAILABLE/);
  assert.equal(await abort(second),second.storage_path);
  await db.query("update pet_alert_community_sightings set status='sighting_open' where id=$1",[report]);
  const retry = await prepare(report,actor,1);
  assert.notEqual(retry.storage_path,second.storage_path);
  assert.equal(await abort(second),null);
  await assert.rejects(()=>finalize(second),/STALE/);
  await object(retry); await finalize(retry);
  await db.query('delete from pet_alert_community_sighting_media where id=(select media_id from pet_alert_community_photo_uploads where id=$1)',[first.id]);
  await assert.rejects(()=>prepare(report),/REMOVED/);
  const pending = await prepare(report,actor,2); await object(pending);
  await db.exec("set role authenticated; select set_config('request.jwt.claim.role','authenticated',false)");
  await assert.rejects(()=>prepare(report),/permission denied/);
  await assert.rejects(()=>db.query("insert into storage.objects values('pet-alert-media',$1)",[`${report}/sos-v1/forged.jpg`]),/row-level security/);
  assert.equal((await db.query('select * from storage.objects where name=$1',[pending.storage_path])).rows.length,0);
  assert.equal((await db.query('select * from storage.objects where name=$1',[retry.storage_path])).rows.length,1);
  assert.equal((await db.query('delete from storage.objects where name=$1 returning *',[retry.storage_path])).rows.length,0);
  await db.query("insert into storage.objects values('pet-alert-media',$1)",[`${report}/legacy.jpg`]);
  await db.exec('reset role');
  await db.exec('set role anon');
  await assert.rejects(()=>prepare(report),/permission denied/);
  await assert.rejects(()=>db.query('select * from pet_alert_community_photo_uploads'),/permission denied/);
  assert.equal((await db.query('select * from storage.objects where name=$1',[pending.storage_path])).rows.length,0);
  assert.equal((await db.query('select * from storage.objects where name=$1',[retry.storage_path])).rows.length,1);
  await db.exec('reset role');
  await db.query('update pet_alert_community_sightings set share_enabled=false where id=$1',[report]);
  await db.exec('set role anon');
  assert.equal((await db.query('select * from storage.objects where name=$1',[retry.storage_path])).rows.length,0);
  await db.exec('reset role');
  await assert.rejects(()=>db.query("insert into pet_alert_community_sighting_media(storage_path) values($1)",[`${report}/sos-v1/forged.jpg`]),/SERVER_MEDIA_REQUIRED/);
  await db.exec("select set_config('request.jwt.claim.role','service_role',false)");
  await db.query("update pet_alert_community_photo_uploads set lease_until=now()-interval '1 minute' where id=$1",[pending.id]);
  await assert.rejects(()=>finalize(pending),/STALE/);
  await db.query('update pet_alert_community_photo_uploads set attempt_count=5 where id=$1',[pending.id]);
  await assert.rejects(()=>prepare(report,actor,2),/RATE_LIMITED/);
  for (let n=0;n<6;n++) await prepare(await seed());
  await assert.rejects(()=>prepare(report,actor,2,'c'.repeat(64)),/RATE_LIMITED/);
  console.log('PASS: SQL migration, authorization, reservations, replay, audit, stale cleanup, deleted media, limits and restrictive Storage policies (isolated fixtures; no hosted concurrency).');
} finally { await db.close(); }
